source: .
collections_config:
  pages:
    path: ''
    icon: wysiwyg
    disable_url: false
    _inputs:
      $.meta.title:
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Etc/UTC
output_dir: _site
common_config:
  name: My Portfolio
